### ISSUE TITLE
Split theme up into plugins + theme

### ISSUE THREAD

**Issue by bramwillemse** [bramwillemse/bw-blog#4]
It would be nice to split this theme into function and theming (plugin(s) and theme). 

In this way changing theme wouldn't necessarily influence architecture (like WordPress Custom Post Type-structure).

**Comment by bramwillemse** [comment]
First idea: 
- Base plugin (basic 'normalize'-like plugin, used in other websites)
- BRW Architecture-plugin (post types, ACF, and other structural enhancements)
- Bramster theme (with presentation & styling related functions)

**Comment by stefthoen** [comment]
You could move the base plugin to its own repo and add it through Composer.

When you're deciding about what part of the theme functionality you have to move to its own plugin, it helps to think about what part of that functionality transforms the data in your database. So if you have custom post types, taxonomies and shortcodes, they all transform data in some way. If you ever want to switch themes, your new theme needs that functionality to properly show all the changes made to the data. So that's why you want them in seperate plugins.

**Comment by bramwillemse** [comment]
The split up is done, further improvements will come later and separated in theme and plugins.
